version: '3.8'
services:
  gateway:
    build: gateway
    image: shareit-gateway-image
    container_name: shareit-gateway-container
    ports:
      - "8080:8081"
    depends_on:
      - server
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - SHAREIT_SERVER_URL=http://server:9091

  server:
    build: server
    image: shareit-server-image
    container_name: shareit-server-container
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
#      - /var/lib/postgresql/data/
    ports:
      - "9090:9091"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  db:
    image: postgres:16-alpine
    container_name: Shareit-db-container
    ports:
      - "6541:5432"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=shareit