CREATE TABLE IF NOT EXISTS public.users
(
    user_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     CHARACTER varying(512) NOT NULL,
    user_name CHARACTER varying(50),
    CONSTRAINT users_email_unq UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.items
(
    item_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id   INTEGER,
    item_name       CHARACTER varying(50),
    description     CHARACTER varying(1024),
    available       boolean,
    request_id      INTEGER
);
